apiVersion: v1
kind: Service

metadata:
  name: student-management-service

spec:
  type: NodePort

  selector:
    app: student-management-app

  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30080
